library/oauth_project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

library/oauth_project/oauth_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

library/oauth_project/accounts/models.py
from django.db import models

# Create your models here.

library/oauth_project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login, logout as auth_logout

# Create your views here.
def main(request):
    return render(request, 'accounts/main.html')

def login(request):
    if request.method == "POST":
        auth_id = request.POST.get('auth_id')
        auth_pwd = request.POST.get('auth_pwd')
        user = authenticate(request, username=auth_id, password=auth_pwd)
        if user is not None:
            auth_login(request, user)
            return redirect('accounts:main')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout(request):
    auth_logout(request)
    return redirect('accounts:main')

library/oauth_project/accounts/templates/accounts/login.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="auth_id">
        <input type="password" name="auth_pwd">
        <input type="submit" value="Login">
    </form>

    <a href="{% provider_login_url 'kakao' method='oauth2' %}">Kakao_login</a>
</body>
</html>

library/oauth_project/accounts/templates/accounts/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>AllAuth</title>
</head>
<body>
    <div>
        <a href="{% url 'accounts:main' %}">Home</a>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">Login</a>
        {% endif %}
    </div>

    <h1>Main</h1>
    {% if user.is_authenticated %}
        <p>{{request.user}}님, 로그인하셨습니다.</p>
    {% else %}
        <p>학습 목적이기에 꾸며지지 않았습니다.</p>
    {% endif %}
</body>
</html>